spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/road-app?zeroDateTimeBehavior=convertToNull
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update #update #create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 30일 = 2592000 * 1000(ms)
  expired-time-ms: ${JWT_EXPIRED_TIME_MS}

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
